[environments]
  [environments.development]
    name = "sample-spring"
    namespace = "development"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""
