# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
  basedomain: apps.opspresso.com
hpa:
  enabled: true
  min: 2
  max: 30
  cpu: 50
env:
# - name: PROFILE
#   valueFrom:
#     configMapKeyRef:
#       name: sample-spring
#       key: PROFILE
# - name: SLACK_WEBHOOK
#   valueFrom:
#     configMapKeyRef:
#       name: sample-spring
#       key: SLACK_WEBHOOK
# - name: SLACK_CHANNEL
#   valueFrom:
#     configMapKeyRef:
#       name: sample-spring
#       key: SLACK_CHANNEL
